[project]
name = "bilianalyzer"
version = "0.1.0"
description = "A Python-Implemented Command Line Bilibili Comment Fetch and Analysis Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bilibili-api-python>=17.3.0",
]

[tool.black]
max_line_length = 120